In [0]:
import numpy as np
mtx = np.array([[1, 2, 3],        # 3×3の行列を作成
                [4, 5, 6],
                [7, 8, 9]],
               dtype = np.float)

In [0]:
mtx

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [0]:
mtx + 10  # 足し算

array([[ 11.,  12.,  13.],
       [ 14.,  15.,  16.],
       [ 17.,  18.,  19.]])

In [0]:
mtx - 10  # 引き算

array([[-9., -8., -7.],
       [-6., -5., -4.],
       [-3., -2., -1.]])

In [0]:
mtx * 2  # 乗算

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5]])

In [0]:
mtx / 2   # 除算

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5]])

In [0]:
mtx % 2   # 剰余

array([[ 1.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  1.]])