In [1]:
import numpy as np

In [9]:
x = np.array([1, 2, 3, 4, 5],  # 配列要素
             dtype = np.float  # 実数型(float)にする
            )
print(x)

[ 1.  2.  3.  4.  5.]


In [3]:
x + 10

array([ 11.,  12.,  13.,  14.,  15.])

In [4]:
x - 1

array([ 0.,  1.,  2.,  3.,  4.])

In [5]:
x * 10

array([ 10.,  20.,  30.,  40.,  50.])

In [6]:
x / 2

array([ 0.5,  1. ,  1.5,  2. ,  2.5])

In [7]:
x // 2

array([ 0.,  1.,  1.,  2.,  2.])

In [8]:
x % 2

array([ 1.,  0.,  1.,  0.,  1.])